### ISSUE TITLE
Got issue when try it in Angular 10

### ISSUE THREAD

**Issue by JJiangZS** [ckeditor/ckeditor4-angular#240]
Hi,
I got an issue in Angular 10, how can I do on this case?

package.json
"ckeditor4-angular": "^3.2.2",
"@angular/core": "~10.0.3",
"@angular/forms": "~10.0.3",

ERROR Error: Uncaught (in promise): Error: http://localhost:4200/<my app path>/config.js?t=N1FB load failed with status 404
Error: http://localhost:4200/<my app path>/config.js?t=N1FB load failed with status 404
    at index.js:87:15
    at ZoneDelegate.invoke (zone.js:386:30)
    at Object.onInvoke (core.js:27149:33)
    at ZoneDelegate.invoke (zone.js:385:36)
    at Zone.run (zone.js:143:47)
    at zone.js:891:38
    at ZoneDelegate.invokeTask (zone.js:421:35)
    at Object.onInvokeTask (core.js:27137:33)
    at ZoneDelegate.invokeTask (zone.js:420:40)
    at Zone.runTask (zone.js:188:51)
    at resolvePromise (zone.js:832:39)
    at resolvePromise (zone.js:784:21)
    at zone.js:894:21
    at ZoneDelegate.invokeTask (zone.js:421:35)
    at Object.onInvokeTask (core.js:27137:33)
    at ZoneDelegate.invokeTask (zone.js:420:40)
    at Zone.runTask (zone.js:188:51)
    at drainMicroTaskQueue (zone.js:601:39)
defaultErrorLogger @ core.js:4081
10257723-5969-46d6-9653-51e00b8f6949:1 
       Refused to apply style from 'http://localhost:4200/<my app path>/skins/moono-lisa/editor.css?t=N1FB' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
lang/zh-cn.js?t=N1FB:1 
       Failed to load resource: the server responded with a status of 404 (Not Found)
core.js:4081 
       ERROR Error: Uncaught (in promise): TypeError: Cannot set properties of undefined (setting 'dir')
TypeError: Cannot set properties of undefined (setting 'dir')
    at Object.f (ckeditor.js:248:54)
    at n (ckeditor.js:249:111)
    at Array.x (ckeditor.js:249:266)
    at w (ckeditor.js:249:350)
    at CKEDITOR.env.ie.g.$.onerror (ckeditor.js:250:354)
    at manualInvokeElementOnError (common.js:71:13)
    at error (common.js:216:19)
    at index.js:86:9
    at ZoneDelegate.invoke (zone.js:386:30)
    at Object.onInvoke (core.js:27149:33)
    at resolvePromise (zone.js:832:39)
    at resolvePromise (zone.js:784:21)
    at zone.js:894:21
    at ZoneDelegate.invokeTask (zone.js:421:35)
    at Object.onInvokeTask (core.js:27137:33)
    at ZoneDelegate.invokeTask (zone.js:420:40)
    at Zone.runTask (zone.js:188:51)
    at drainMicroTaskQueue (zone.js:601:39)
defaultErrorLogger @ core.js:4081
10257723-5969-46d6-9653-51e00b8f6949:1 
        
       Refused to apply style from 'http://localhost:4200/<my app path>/skins/moono-lisa/editor.css?t=N1FB' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
ERROR Error: Uncaught (in promise): TypeError: Cannot set properties of undefined (setting 'dir')
TypeError: Cannot set properties of undefined (setting 'dir')
    at Object.f (ckeditor.js:248:54)
    at n (ckeditor.js:249:111)
    at Array.x (ckeditor.js:249:266)
    at w (ckeditor.js:249:350)
    at CKEDITOR.env.ie.g.$.onerror (ckeditor.js:250:354)
    at manualInvokeElementOnError (common.js:71:13)
    at error (common.js:216:19)
    at index.js:86:9
    at ZoneDelegate.invoke (zone.js:386:30)
    at Object.onInvoke (core.js:27149:33)
    at resolvePromise (zone.js:832:39)
    at resolvePromise (zone.js:784:21)
    at zone.js:894:21
    at ZoneDelegate.invokeTask (zone.js:421:35)
    at Object.onInvokeTask (core.js:27137:33)
    at ZoneDelegate.invokeTask (zone.js:420:40)
    at Zone.runTask (zone.js:188:51)
    at drainMicroTaskQueue (zone.js:601:39)
defaultErrorLogger @ core.js:4081
handleError @ core.js:4129

**Comment by KarolDawidziuk** [comment]
Hello @JJiangZS 

I'm sorry for the late reply.

Could you please provide a list of **all** dependencies with versions? This will allow us to see more quickly where the problem might be.

**Comment by jacekbogdanski** [comment]
I'm closing the issue due to no feedback from the reporter.
