### ISSUE TITLE
e2e tests are not starting

### ISSUE THREAD

**Issue by Dumluregn** [ckeditor/ckeditor4-angular#60]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Run `ng e2e`

### Expected result

e2e tests on Protractor are running.

### Actual result

Error about wrong browser version appears. Seems like `chromedriver` should be updated.

```
[09:56:42] E/launcher - SessionNotCreatedError: session not created: Chrome version must be between 71 and 75
  (Driver info: chromedriver=2.46.628411 (3324f4c8be9ff2f70a05a30ebc72ffb013e1a71e),platform=Mac OS X 10.14.6 x86_64)
    at Object.checkLegacyResponse (/Users/darek/Documents/workspace/ckeditor/ckeditor4-angular/node_modules/selenium-webdriver/lib/error.js:546:15)
    at parseHttpResponse (/Users/darek/Documents/workspace/ckeditor/ckeditor4-angular/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/Users/darek/Documents/workspace/ckeditor/ckeditor4-angular/node_modules/selenium-webdriver/lib/http.js:441:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
From: Task: WebDriver.createSession()
    at Function.createSession (/Users/darek/Documents/workspace/ckeditor/ckeditor4-angular/node_modules/selenium-webdriver/lib/webdriver.js:769:24)
    at Function.createSession (/Users/darek/Documents/workspace/ckeditor/ckeditor4-angular/node_modules/selenium-webdriver/chrome.js:761:15)
    at Direct.getNewDriver (/Users/darek/Documents/workspace/ckeditor/ckeditor4-angular/node_modules/protractor/built/driverProviders/direct.js:77:33)
    at Runner.createBrowser (/Users/darek/Documents/workspace/ckeditor/ckeditor4-angular/node_modules/protractor/built/runner.js:195:43)
    at q.then.then (/Users/darek/Documents/workspace/ckeditor/ckeditor4-angular/node_modules/protractor/built/runner.js:339:29)
    at _fulfilled (/Users/darek/Documents/workspace/ckeditor/ckeditor4-angular/node_modules/q/q.js:834:54)
    at /Users/darek/Documents/workspace/ckeditor/ckeditor4-angular/node_modules/q/q.js:863:30
    at Promise.promise.promiseDispatch (/Users/darek/Documents/workspace/ckeditor/ckeditor4-angular/node_modules/q/q.js:796:13)
    at /Users/darek/Documents/workspace/ckeditor/ckeditor4-angular/node_modules/q/q.js:556:49
    at runSingle (/Users/darek/Documents/workspace/ckeditor/ckeditor4-angular/node_modules/q/q.js:137:13)
[09:56:42] E/launcher - Process exited with error code 199
```

## Other details

* OS: macOS
* Integration version: `1.0.0-beta.2`
* CKEditor version: 4.12.1

**Comment by f1ames** [comment]
It was already done in https://github.com/ckeditor/ckeditor4-angular/commit/567520fca3b7ddced186f50267bb9b71920fdec7#diff-354f30a63fb0907d4ad57269548329e3R22-R26 for CI so we should probably follow the similar approach in local env (until any new and more proper solution came up).

**Comment by Dumluregn** [comment]
Well, there is good news and bad news. Good - there is a new Protractor patch (`5.4.3` instead of `5.4.2`, which allows using newer Chrome versions without hassle. Bad news is that those tests are failing now, so I will fix them before creating PR.

**Comment by f1ames** [comment]
> Well, there is good news and bad news. Good - there is a new Protractor patch (`5.4.3` instead of `5.4.2`, which allows using newer Chrome versions without hassle. Bad news is that those tests are failing now, so I will fix them before creating PR.

Seems, like a patch version so it shouldn't have any significant API changes :thinking: But maybe there is something wrong with our tests too. I recall when working on fixing the similar issue on CI new `chromedriver` caused some tests to fail indded (so it might e the issue of the newer Chrome version used by the newer `protractor` version).
